### ISSUE TITLE
Excpetion if no A record was found

### ISSUE THREAD

**Issue by er4z0r** [heywoodlh/urlscan-py#10]
I just had to test a large bunch of domains, some of which apparently do not have an A record (i.e. they merely got registered to claim the domain, but are not used).

The following command was used to retrieve the results using urlscan:
`while read u ; do urlscan retrieve --db urlscan.db --uuid "$u" --api $URLSCAN_API_KEY --dir $PWD/urlscan-results --dom --png --summary | tee "$u" ;done<uuids.txt`

For some domains this resulted in the following error when retrieving the results:

```
  File "/home/foo/.local/bin/urlscan", line 352, in <module>
    main()
  File "/home/foo/.local/bin/urlscan", line 347, in main
    query(args.uuid)
  File "/home/foo/.local/bin/urlscan", line 299, in query
    print_summary(response.json())
  File "/home/foo/.local/bin/urlscan", line 257, in print_summary
    print("IP Address: " + page_ip)
TypeError: can only concatenate str (not "NoneType") to str
```
I am aware that this might be a more rare use-case (most people probably check URLs that they know point to something). However, in the interest of keeping the output clean, it would  be great if this error would be avoided.

**Comment by heywoodlh** [comment]
Sure, that makes sense, I will add an exception for this type of error. Will let you know when this is updated.

Sorry, I didn't see this issue until just now!

**Comment by heywoodlh** [comment]
Added an `if` statement that will only print out the summary if there is an IP associated with the page of a site. Otherwise, the domain shouldn't actually render a web page if there is no IP address associated with it.

Commit here: dc31d66bb3e79

Here's an example of how the workflow looks now with the `--summary` flag enabled on a domain that doesn't have an A Record/IP Address associated with it:

```bash
$ ./urlscan scan --url null.nullwebsite.com
{
  "message": "Submission successful",
  "uuid": "5d8b2ea5-183f-4ab2-8a11-4cf0124c315d",
  "result": "https://urlscan.io/result/5d8b2ea5-183f-4ab2-8a11-4cf0124c315d/",
  "api": "https://urlscan.io/api/v1/result/5d8b2ea5-183f-4ab2-8a11-4cf0124c315d/",
  "visibility": "private",
  "options": {
    "useragent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36"
  },
  "url": "http://null.nullwebsite.com"
}

$ ./urlscan retrieve --uuid 5d8b2ea5-183f-4ab2-8a11-4cf0124c315d --summary
$
```

Notice it doesn't output anything. That should solve the nasty TypeError message. Let me know if that works for you or if you have any other suggestions.

Feel free to close this issue if that works. :) I'll leave the issue open for a few days and close if I don't hear back.
