### ISSUE TITLE
Urlscan does not work (Arch Linux)

### ISSUE THREAD

**Issue by ZeroDot1** [heywoodlh/urlscan-py#2]
It is not possible to enter the API key, even deleting the files did not help. 

Terminal Output:
```bash
$ cd
[user@ax ~]$ git clone https://github.com/heywoodlh/urlscan-py
Klone nach 'urlscan-py' ...
remote: Counting objects: 111, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 111 (delta 2), reused 6 (delta 2), pack-reused 105
Empfange Objekte: 100% (111/111), 27.42 KiB | 252.00 KiB/s, Fertig.
Löse Unterschiede auf: 100% (60/60), Fertig.
[user@ax ~]$ cd urlscan-py
[user@ax urlscan-py]$ sudo pip3 install -r requirements.txt
[sudo] Passwort für user: 
Requirement already satisfied: certifi==2017.11.5 in /usr/lib/python3.6/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied: chardet==3.0.4 in /usr/lib/python3.6/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied: idna==2.6 in /usr/lib/python3.6/site-packages (from -r requirements.txt (line 3))
Requirement already satisfied: requests==2.18.4 in /usr/lib/python3.6/site-packages (from -r requirements.txt (line 4))
Requirement already satisfied: urllib3==1.22 in /usr/lib/python3.6/site-packages (from -r requirements.txt (line 5))
[user@ax urlscan-py]$ python urlscan.py scan --url https://google.com
Traceback (most recent call last):
  File "urlscan.py", line 57, in <module>
    urlscan_api = ''.join(db_extract)
TypeError: can only join an iterable
[user@ax urlscan-py]$ 

```

```bash
$ inxi -F
System:    Host: ax Kernel: 4.15.3-2-ARCH x86_64 bits: 64
           Desktop: Cinnamon 3.6.7  Distro: Antergos Linux
Machine:   Device: desktop Mobo: ASUSTeK model: A68HM-PLUS v: Rev X.0x serial: N/A
           UEFI [Legacy]: American Megatrends v: 1903 date: 08/04/2017
CPU:       Quad core AMD A10-6790K APU with Radeon HD Graphics (-MCP-) 
           cache: 8192 KB
           clock speeds: max: 4000 MHz 1: 3646 MHz 2: 3471 MHz 3: 1994 MHz
           4: 1981 MHz

```

**Comment by heywoodlh** [comment]
Hmm. This is odd. I just ran through the same steps on my Arch laptop and I can't seem to replicate the same issue. Let me try it on a fresh VM and follow up with my results.

**Comment by ZeroDot1** [comment]
If you don't enter an API key the first time and then try again, the problem should occur. 
The best solution is to add a new parameter to enter the API key.

`python urlscan.py add --api-key THEAPIKEY`

**Comment by heywoodlh** [comment]
Ah, I see. I will set up an 'init' subparser and I will notify you when it is completed.

**Comment by ZeroDot1** [comment]
Good work :+1:

**Comment by heywoodlh** [comment]
I have committed code with an init parser and updated the README on how to use it. 
In short, you can add the API entry to the database or overwrite the entry if it exists using `python urlscan.py init --api_key xxxxxx-xxxx-xxxx-xxxxxxxxxx`. 

Hopefully this solves your problem. Also, if you have any feedback on what you would prefer instead of what I have added please let me know.

**Comment by heywoodlh** [comment]
Also, I have added an `--api` flag to each parser. So that way you can run a scan without storing the entry in the database.

**Comment by ZeroDot1** [comment]
Thank you so much, I'll try it out as soon as I can.

**Comment by ZeroDot1** [comment]
@heywoodlh It doesn't seem to be working properly yet.
```bash
$ git clone https://github.com/heywoodlh/urlscan-py.git
Klone nach 'urlscan-py' ...
remote: Counting objects: 115, done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 115 (delta 4), reused 6 (delta 2), pack-reused 105
Empfange Objekte: 100% (115/115), 29.29 KiB | 329.00 KiB/s, Fertig.
Löse Unterschiede auf: 100% (62/62), Fertig.
[user@ax ~]$ cd urlscan-py
[user@ax urlscan-py]$ sudo pip3 install -r requirements.txt
[sudo] Passwort für user: 
Requirement already satisfied: certifi==2017.11.5 in /usr/lib/python3.6/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied: chardet==3.0.4 in /usr/lib/python3.6/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied: idna==2.6 in /usr/lib/python3.6/site-packages (from -r requirements.txt (line 3))
Requirement already satisfied: requests==2.18.4 in /usr/lib/python3.6/site-packages (from -r requirements.txt (line 4))
Requirement already satisfied: urllib3==1.22 in /usr/lib/python3.6/site-packages (from -r requirements.txt (line 5))
[user@ax urlscan-py]$ python urlscan.py init --api_key xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
Traceback (most recent call last):
  File "urlscan.py", line 204, in <module>
    main()
  File "urlscan.py", line 192, in main
    initialize()
  File "urlscan.py", line 94, in initialize
    get_key_value()
  File "urlscan.py", line 88, in get_key_value
    urlscan_api = ''.join(db_extract)
TypeError: can only join an iterable
[user@ax urlscan-py]$ python urlscan.py scan --url https://google.com
Traceback (most recent call last):
  File "urlscan.py", line 204, in <module>
    main()
  File "urlscan.py", line 192, in main
    initialize()
  File "urlscan.py", line 104, in initialize
    get_key_value()
  File "urlscan.py", line 88, in get_key_value
    urlscan_api = ''.join(db_extract)
TypeError: can only join an iterable
[user@ax urlscan-py]$ 

```

**Comment by heywoodlh** [comment]
Tried it out on a fresh install of Antergos. When I ran `python urlscan.py init --api_key` command the very first time I get the TypeError. This is caused because there were other functions being executed before the API key was saved to the database and the functions are trying to use an entry from the database that didn't exist at the time. However, the entry is still saved despite the first error and you should be able to run commands after the first error. 

I somehow missed this so I just fixed it with my most recent commit. Also, I made the TypeError more verbose by printing out that an invalid API key value is detected in the database. Hopefully, that helps.

The TypeError is caused when an invalid API key value is detected. If you could run some Python commands to check if the value entered into the database is correct that would be great. Here is a Python snippet that you can run to print the API key value in the database (assuming you use the default database connection):

```
❯ python
Python 3.6.4 (default, Jan  5 2018, 02:35:40)
[GCC 7.2.1 20171224] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlite3, pathlib
>>> urlscan_dir = str(pathlib.Path.home()) + '/.urlscan'
>>> urlscan_default_db = urlscan_dir + '/urlscan.db'
>>> conn = sqlite3.connect(urlscan_default_db)
>>> c = conn.cursor()
>>> c.execute("SELECT * FROM api")
<sqlite3.Cursor object at 0x7f73a7c08490>
>>> print(c.fetchone())
('xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',)
>>>
```

If you could run these commands and verify that the API key printed out is the correct urlscan.io API key that would be great. Perhaps there is some bug in my code that is putting the wrong value in the database and I can't see it. 

Also, I'm curious if you have the same issue when you use the `--api` flag on each command you run. If you could try using that flag and see if it temporarily fixes the problem that would be really helpful as well!

Thanks for your patience on this. Hopefully this gives you some information that is useful and helps us nail down exactly what the issue is.

**Comment by ZeroDot1** [comment]
Since the last update it works very good, no more errors after deleting the database file, and creating a new file.
The API key could be entered without any problems. 
Thank you very much for your work, thank you.
:+1:
